services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
    - ./data:/dgraph
    ports:
    - 25080:5080
    - 26080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
    profiles:
    - production
    - dev
    

  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - ./data:/dgraph
    ports:
    - 28080:8080
    - 29080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=0.0.0.0/0
    profiles:
    - production
    - dev

  ratel:
    image: dgraph/ratel:latest
    ports:
    - 38000:8000
    profiles:
    - dev
    
  graphiql-playground:
    build:
      context: ./graphiql_playground
    ports:
    - 24080:80
    volumes:
    - ./config/graphiql-playground/default.conf:/etc/nginx/conf.d/default.conf:ro            
    profiles:
    - dev

  monitor:
    image: m2tec/dando-dao-monitor
    build:
      context: ./monitor
    environment:
    - VITE_GRAPH_URL="https://dgraph.m2tec.nl/graphql"
    - LOG_FOLDER="/logs/monitor/"
    volumes:
    - ./logs/monitor/:/logs/monitor/
    profiles:
    - production

  server:
    image: m2tec/dando-dao-server
    build:
      context: ./
    ports:
    - "28888:80"
    volumes:
    - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro      
    restart: always
    profiles:
    - production
