services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - ./data:/dgraph
    ports:
      - 25080:5080
      - 26080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
    
  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - ./data:/dgraph
    ports:
      - 28080:8080
      - 29080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:27080 --zero=zero:25080 --security whitelist=10.89.0.0/16

  # ratel:
  #   image: dgraph/ratel:latest
  #   ports:
  #     - 8000:8000

  server:
    build:
      context: ./
    ports:
      - "28888:80"
    volumes:
    - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro      
    restart: always
